### ISSUE TITLE
find a error , when init the queue

### ISSUE THREAD

**Issue by wustzhy** [buaa0300/QSKitDemo#1]
file:    QSDispatchQueue.m
line:   104
wrong code: 
            queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0);
right result:
            _queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0);

**Comment by buaa0300** [comment]
Thank you very much, I have fixed it. The new project address is https://github.com/buaa0300/QSDispatchQueue.
